### ISSUE TITLE
(Intermittent) - Incorrect season number in filenames 

### ISSUE THREAD

**Issue by BradMJustice** [mosswg/dropout-dl#14]
**Describe the bug**
When downloading a season (or its individual episodes), sometimes a wildly incorrect season number is used in the filename.

**To Reproduce**
Run command `docker run --rm -it -v $PWD/login:/app/login -v $PWD/out:/Downloads dropout-dl:latest --output-directory /Downloads --captions --verbose -q 1080p -s https://www.dropout.tv/dimension-20/season:5
`
This is intermittent does not happen with all seasons of all shows. Anecdotally, it appears that for every season that this happens, logs will show many instances of the message "ERROR: Could not find start of substring" when parsing for episodes.

**Expected behavior**
File names should have `S05EXX`. In my case, they had `S52EXX`

**Desktop (please complete the following information):**
Windows 11

Possibly related to #5

**Comment by khurdkorkmaz** [comment]
I also just ran into this.
When downloading the series "Make Some Noise" the folder for Season 1 was created, but all media was marked as "Season 19"

**Comment by mosswg** [comment]
I just pushed a commit that I think fixes this issue. I haven't been able to reproduce this issue myself. So, please let me know if this is still happening with this new commit. If no one has reported this happening in within a month, I'll close this issue.
