### ISSUE TITLE
Unable to determine quality of Seasons or Series

### ISSUE THREAD

**Issue by khurdkorkmaz** [mosswg/dropout-dl#17]
**Describe the bug**
When running dropout-dl, the application is able to take the URL and determine the episode listings, but is unable to actually download. However, when running the application with a single episode link it has no trouble.

**To Reproduce**
Run command: ./dropout-dl --output-directory "/mnt/plexcontent/TV Shows/" --series https://www.dropout.tv/game-changer

**Expected behavior**
Media downloaded

**Screenshots**
![image](https://github.com/mosswg/dropout-dl/assets/24235658/7f1c7515-e6ef-4c2c-896c-ef6769cf6502)

Episode Example:
![image](https://github.com/mosswg/dropout-dl/assets/24235658/e21fa484-6ded-4fcf-b2c1-d70d4feadace)

**Desktop (please complete the following information):**
Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic

**Comment by mosswg** [comment]
Hi, thanks for submitting an issue. I just pushed a commit that fixes this on my end. Could you check and make sure this fixes it for you?

**Comment by khurdkorkmaz** [comment]
Everything looks good now! Thank you for your update.
