### ISSUE TITLE
Requesting login file when it exists.

### ISSUE THREAD

**Issue by Arguens89** [mosswg/dropout-dl#2]
**Describe the bug**
The docker application asking me for login file even when login file exists.

**To Reproduce**
I've tried to follow the steps, compiled the docker, filled in the variables, filled in the login file.

**Expected behavior**
The docker application asking me for login file even when login file exists.

**Screenshots**

**Desktop (please complete the following information):**
Ubuntu 22.04.2 LTS"
Docker

**Smartphone (please complete th
![cmd_3p6DT0ib4k](https://user-images.githubusercontent.com/28986718/234259647-61526b9e-4e98-4380-bfc3-344649028a7f.png)
e following information):**

**Additional context**
Thank you for doing this program/docker style. I would love for it to work.

**Comment by mosswg** [comment]
The docker command you used tells docker that the login file is at the path `./login` but you cat out the file `./login/login`. The solution is to either change that part of the docker command from `-v $PWD/login:/app/login` to `-v $PWD/login/login:/app/login` or move your login file to `./login`. Please let me know if this fixes your issue or if there is anything else I can help with.

**Comment by Arguens89** [comment]
That was my bad. Thank you for clarification. I didn't understand you can volume mount only one file. Thank you for your help and I apologize.
