### ISSUE TITLE
JSON error after downloading 10-12 episodes

### ISSUE THREAD

**Issue by Loveshock** [mosswg/dropout-dl#23]
Downloading a season throws a terminate error, and it happens inconsistently. Tried on both a Linux-built version and with the Docker container. This has happened inconsistently with several seasons of _Game Changer_ - I've tried 3, 4, and 5 and both keep happening regularly.

Pretty consistently, it happens around 10 episodes/videos in. Season 3 regularly fails around *The Substitute* or *Three for the Price of One*, Season 4 regularly fails around *Survivor Pt. 1* or *Pt. 2*, as examples. I tried downloading *Dirty Laundry* as a series, as well, and it failed around *Who Had Covid-Compliant Sex?*, which is the 11th episode in the series (episode 4 of season 2). 

My working theory is that this is some form of rate-limit, but I'm not quite sure.

![image](https://github.com/mosswg/dropout-dl/assets/79419311/5373f258-8aa1-4dd1-a163-375e04f86ef7)

![image](https://github.com/mosswg/dropout-dl/assets/79419311/05b8822d-8701-4104-997a-3e50d60efbb2)

![image](https://github.com/mosswg/dropout-dl/assets/79419311/ad12db97-e78c-4eb8-a0a3-cc410dc80409)

**Comment by variousinputs** [comment]
+1, seeing the same behavior. After 10-11 episodes in 'getting series', the script exits with an error for invalid parsing in JSON. Maybe there needs to be some error handling to be implemented for the program to retry?

**Comment by mosswg** [comment]
This is rate limiting. I'm looking for a way to prevent getting rate limited, since it cuts off access completely for a few minutes once being rate limited. So we can't just retry after error, although I will add some error handling for parse errors. I should have something out soon.
