### ISSUE TITLE
Episodes hidden behind "Show more" not downloaded during a series download

### ISSUE THREAD

**Issue by RogueBurger** [mosswg/dropout-dl#4]
**Describe the bug**
When I was downloading the Breaking News series, I noticed that season 3 episode 26 got skipped. Looking at the page for that season, it appears that the season only shows the first 24 episodes and that the final episode is hidden until you click the Show More button at the bottom of the page. I assume that is why the scraper was unaware of it. I was able to download the episode on its own just fine as a temporary work around.

**To Reproduce**
1. run `docker run --rm -it -v $PWD/login:/app/login -v $PWD/out:/Downloads dropout-dl:latest --output-directory /Downloads --captions -S https://www.dropout.tv/breaking-news-no-laugh-newsroom`
2. check output/directory and see it skip from S03E25 to S04E01

**Expected behavior**
The Series finds and downloads all the episodes, even the hidden ones.

**Screenshots**
![Screenshot 2023-06-10 222421](https://github.com/mosswg/dropout-dl/assets/9021376/7cdf1f0e-1fa9-46a3-b08b-d548fa036307)
![Screenshot 2023-06-10 222919](https://github.com/mosswg/dropout-dl/assets/9021376/59578cc8-73ed-4ef4-a285-06089a976106)

**Comment by mosswg** [comment]
Hi, thank you for submitting this issue. I just pushed a commit that fixes this on my computer. Please try this and let me know if you are still having any issues. Make sure to re-run the docker build command before running.

**Comment by RogueBurger** [comment]
Yep, all working for me now too! 😄Thanks a bunch for getting that fixed so fast.

**Comment by mosswg** [comment]
Sorry it took so long for me to get to this. I just pushed a commit that fixes this issue. Hope you have no more issues, but if you do, please let me know.
