### ISSUE TITLE
Suggestion: Add option to download captions only

### ISSUE THREAD

**Issue by MisterSheeple** [mosswg/dropout-dl#9]
**Is your feature request related to a problem? Please describe.**
I downloaded some videos before realizing that it was possible to download captions with them, so I don't want to have to download the videos all over again with the captions.

**Describe the solution you'd like**
A simple flag to only download captions and skip downloading the video.

**Comment by BradMJustice** [comment]
Hi there! I find myself needing this same functionality. I have been fiddling with it locally and think I am onto a solution, so I'll be creating a pull request soon.

**Comment by BradMJustice** [comment]
Pull request has been created, I welcome your feedback
#12

**Comment by MisterSheeple** [comment]
Here is a somewhat related issue that I haven't put into a GH issue until now: #13

> Pull request has been created, I welcome your feedback
> #12 

Thank you for the pull. I'll have a look at it when I have a moment to do so.

**Comment by BradMJustice** [comment]
> Here is a somewhat related issue that I haven't put into a GH issue until now: #13

Nice! That was a pretty easy fix, and I've added a fix to my current PR.
